@extends('layouts.main')

@section('titulo', 'Perfil')
@section('css', '/css/perfil.css')
    
@section('conteudo')
    <div class="container">
        <!-- Header Section -->
        <div class="profile-header">
            <h1>Olá, <span></span></h1>
            <div class="profile-picture">

            </div>
        </div>

        <!-- Account Details Section -->
        <section class="account-details">
            <h2>Dados da Conta</h2>
            <form method="POST">
                <div class="form-container">
                    <div class="form-left">
                        <input type="text" name="name" id="name" value="" disabled>
                        <input type="email" name="email" id="email" value="" disabled>
                        <input type="password" name="password" id="password" value="" disabled>
                    </div>
                    <div class="form-right">
                        <input type="tel" name="phone" id="phone" value="" disabled>
                        <input type="text" name="cpf" id="cpf" value="" disabled>
                    </div>
                </div>
                <button type="button" class="edit-btn" id="editBtn">Editar informações</button>
                <button type="submit" class="save-btn" id="saveBtn" style="display: none;">Salvar</button>
            </form>

            <div class="action-buttons">
                <button class="end-session-btn">Encerrar sessão</button>
                <button class="delete-account-btn">Deletar Conta</button>
            </div>
        </section>

        <!-- Tickets Section -->
        <section class="tickets-section">
            <h2>Meus Ingressos</h2>
            <h3>RECENTES</h3>
            <div class="tickets-grid">
                <!-- Ticket cards will be generated by JavaScript -->
            </div>
            <button class="view-more-btn">VER MAIS INGRESSSOS</button>
        </section>
    </div>

    <div class="footer-mob">

        <div class="container-buttons">
            <div class="inicio">
                <a href="./index.php">
                    <i class="fa-solid fa-house"></i>
                    Início
                </a>
            </div>
            <div class="anunciar">
                <a href="./areaV.php">
                    <i class="fa-solid fa-plus"></i>
                    Anunciar
                </a>
            </div>
            <div class="procura">
                <a href="./pesquisa.php">
                    <i class="fa-solid fa-globe"></i>
                    Procurar
                </a>
            </div>
            <div class="ingressos">
                <a href="#">
                    <i class="fa-solid fa-ticket"></i>
                    Ingressos
                </a>
            </div>
            <div class="carrinho-footer">
                <a href="./cart.php">
                    <i class="fa-solid fa-cart-shopping"></i>
                    Carrinho
                </a>
            </div>
            <div class="perfil-mob">
                <a href="#">
                    <i class="fa-solid fa-user"></i>
                    Perfil
                </a>
            </div>
        </div>

    </div>
@endsection

@section('js', 'js/perfil.js')